version: "3.9"


services:
  api:
    build:
      context: .
      dockerfile: WebAPIDocker/Dockerfile
    container_name: test-docker
    ports:
      - "5000:80"
      - "8181:8181"   # WebSocket
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__DefaultConnection=Host=${DB_HOST};Database=${DB_DATABASE};Username=${DB_USERNAME};Password=${DB_PASSWORD};SSL Mode=VerifyFull;Trust Server Certificate=true
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}

    restart: always
  