# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test WebAPIDocker.Tests/WebAPIDocker.Tests.csproj --configuration Release --verbosity normal

    - name: LoginDocker
      if: github.ref == 'refs/heads/production'
      uses: docker/login-action@v2
      with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/production'
      run: |
          docker build -t lephuocbinh123/spending:latest .

    - name: Push Docker image
      if: github.ref == 'refs/heads/production'
      run: |
          docker push lephuocbinh123/spending:latest
          # --- Deploy lên Render ---
    - name: Trigger Render Deploy
      if: github.ref == 'refs/heads/production'
      run:  |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/srv-d3l8mhali9vc73emqlo0/deploys
    
    # --- Deploy lên Azure Web App ---
    - name: Azure Login
      if: github.ref == 'refs/heads/production'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      if: github.ref == 'refs/heads/production'
      run: |
        az webapp config container set \
          --name spending \
          --resource-group spending \
          --container-image-name lephuocbinh123/spending:latest
        az webapp restart --name spending --resource-group spending

